### ISSUE TITLE
Use a TOML file instead of `juliaup.json`?

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/juliaup#127]
TOML is pretty universally used throughout the Julia ecosystem for config files etc. Perhaps it makes sense to also use that for `juliaup`?

**Comment by davidanthoff** [comment]
In the beginning it was actually a toml file :) I think I changed it to JSON because I got confused how objects and vectors map to elements in TOML files, I never really understood that, whereas JSON always seemed more straightforward to me. Not the best reason in the world ;)

One thing is that I _really_ want this to be a file that is not manually edited by users, i.e. I think we should communicate that the schema/format is an implementation detail, and that one should _only_ interface with it via `juliaup`. https://github.com/JuliaLang/juliaup/pull/126 is starting to add an API so that e.g. the VS Code extension can "read" the configuration file without accessing the config file itself, but rather by running `juliaup`. We could easily extend that down the road to also include APIs that install versions etc. So maybe from that point of view the format doesn't matter that much? I completely agree that TOML is nicer if one expects users to edit the file, but in my mind that is not a scenario we should make easier...

So, I'm pretty indifferent at the end of the day. If we were to change it, we would need to make sure everything auto-migrates, we're at 440 users for the Windows Store version, so we need to keep things just working for them. My sense is that there are probably other areas here that we should try to sort out first because they are more important :)

**Comment by KristofferC** [comment]
>  #126 is starting to add an API so that e.g. the VS Code extension can "read" the configuration file without accessing the config file itself, but rather by running juliaup


Do you mean something like https://doc.rust-lang.org/cargo/commands/cargo-metadata.html?

> My sense is that there are probably other areas here that we should try to sort out first because they are more important :)

Alright, let's drop this for now then.

**Comment by davidanthoff** [comment]
> Do you mean something like https://doc.rust-lang.org/cargo/commands/cargo-metadata.html?

Yes, that is pretty similar. Essentially the plan is that the VS Code extension will now first try to run `juliaup api getconfig1`, and that will return a JSON string with information about the default Julia version and all other installed Julia versions. And then we can skip the entire horror of searching in known paths for Julia installations that we have right now.
