### ISSUE TITLE
Autogenerate or pull julia-appxmanifest.xml manifests from julia version xml file

### ISSUE THREAD

**Issue by musm** [JuliaLang/juliaup#13]
Perhaps a github action that checks probes the list and updates the manifests if there is a change (especially relevant for the nighlites)

**Comment by davidanthoff** [comment]
Yeah! I wanted to wait with further automation until I have a better understanding how store submissions actually work, because at the end of the day we'll just want to push whatever we build to the store and let MS handle the download bill ;)

**Comment by davidanthoff** [comment]
What we should do is this: ship https://julialang-s3.julialang.org/bin/versions.json in the box, use that as the source of "truth" for available Julia versions. Then also try to regularly download new versions of that file on the user system, so that we can actually inform about new versions of Julia without updating the store submission.

**Comment by davidanthoff** [comment]
We should explore whether https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-backgroundtasks in combination with https://www.syncfusion.com/succinctly-free-ebooks/msix-succinctly/move-your-application-forward-with-msix might be a good way to download the `versions.json`.

**Comment by davidanthoff** [comment]
Essentially a dup of https://github.com/JuliaLang/juliaup/issues/131
