### ISSUE TITLE
Make the "Version" entries in `juliaup.json` be valid semver versions

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/juliaup#140]
Right now, the versions in `juliaup.json` are written like `"Version": "1.6.2+0~x64"`. I don't really understand the purpose behind the `~` stuff and further, this is not a valid semver version string. I think it would be better if they were valid semver versions because then they could be treated as `semver::Version` throughout the code base instead of as strings.

I started a bit with this here: https://github.com/KristofferC/juliaup/tree/kc/types

Not sure what to do about backwards compatibility. There is probably some good rusty way of versioning schemas like this.

**Comment by davidanthoff** [comment]
We need a way to distinguish between different platform builds, so this just means "the x64" version. Alternative values are `x86` and down the road something for arm.

**Comment by KristofferC** [comment]
Yes, I understand that. And I am saying it would be good to provide that in the build entry of a semver version specification.

**Comment by davidanthoff** [comment]
Ah, sorry, didn't get that!

Yes, I think that would actually work. I already use the build part of semver to store a "juliaup packaging build" number, currently all 0 (so that is the `+0` part). The idea behind that is that we might make an error in packaging at some point, and then this build number would allow us to swap these things out on client systems without the need to have a new Julia version. So say we discover that we made some mistake in packaging 1.6.1, then we could create a new tarball, register that as `1.6.1+1`, and then update all channels that point to `1.6.1+0` to point to `1.6.1+1`, and push that out in that way.

BUT, I think we could just expand on that, so that the build part would be say `0-x64`. So first the existing build number, then dash (which I think is valid) and then the arch. If we go in and change that, we might also use proper arch strings? When I started this I just used `x64` and `x86`, but it might make more sense to actually use something that is more standard and also used by say BinaryBuilder.jl?

So I think we could make that change everywhere where there is actually a version used. For the channel names, though, we could stick with the old pattern? They are just opaque ids in any case, with no semantic meaning to anything in them. If we do that, then I actually don't think this would involve any user-visible change at all.

> Not sure what to do about backwards compatibility. There is probably some good rusty way of versioning schemas like this.

That would be nice :) We should probably also add a `schemaversion` to `juliaup.json` while we're at it... Although maybe we should first figure out whether that would make it easier to do some Rust magic on the schema versioning, or just some kind of duck typing idea.
