### ISSUE TITLE
ask whether to try to manage rc files

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/juliaup#172]
Most users will probably want juliaup to munge their rc files (`~/.profile` and `~/.bashrc`) but some users may have some more complex setups (or use different shells) and need to do this themselves. Accordingly, it might be good to ask if juliaup should try and otherwise just tell the user what they need to ensure (i.e. that `~/.juliaup/bin` is in your `PATH`) and let the user do it themselves as they see fit.

Slightly tangential, but it might make sense to have a file called `~/.juliaup/rc/setup.sh` and then source that from both `~/.profile` and `~/.bashrc` since then you can just modify that file in the future to change what gets done instead of having to go back and try to re-edit what's been placed in those files previously.

**Comment by davidanthoff** [comment]
We probably should also move the code that does all of that into Rust, so that `juliaup self install` does that, and then just call that at the end of the shell script that bootstraps things. That would have the additional benefit that instead of using the shell script to install things, someone could also just download `juliaup` by hand, extract it somewhere and then put it onto the `PATH` by calling `juliaup self install`.

**Comment by davidanthoff** [comment]
The latest version of the installer now has an option to make these changes or not, and one can also later change this via `juliaup config modifypath true` (or `false`).
