### ISSUE TITLE
If the `.tool-versions` file exists and has an entry for `julia`, then `juliaup` should use that version of Julia

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/juliaup#181]
I think it would be nice if `juliaup` respected the `.tool-versions` file. For example, suppose that you have a `.tool-versions` file with the following contents:

```
# This is a comment.
nodejs 15.14.0
julia 1.5.4
python 3.7.2 2.7.15 system
ruby 2.5.3 # This is another comment.
rust 1.56.1
```

If you `cd` into a directory that has that `.tool-versions` file (or a subdirectory of a directory that has that file), I think it would be nice if simply running `julia` automatically ran Julia 1.5.4 (instead of the default).

Full documentation of the file syntax is here: https://asdf-vm.com/manage/configuration.html#tool-versions

---

(I think we discussed this a while back on Slack, but it has since been lost to the Slack-hole.)

**Comment by davidanthoff** [comment]
Hm, so I'm a bit wary about this one, TBH. Aren't we running a risk that asdf is then also trying to do something with that information, and then there is the potential for two things getting into each other's way because they both try to do the same thing in some form? So far I had assumed we would just to a Julia specific thing for all of this, just to make sure it can never break because it doesn't have to interop with anything...

**Comment by DilumAluthge** [comment]
Yeah, that's a valid concern. I was just thinking we could get away without having to invent our own file format.

**Comment by DilumAluthge** [comment]
If we do our own Julia-specific thing, we can probably look at what `pyenv` does, at least as a starting point for prior art.

**Comment by StefanKarpinski** [comment]
I'm with @davidanthoff on this one — this feels like it would cause problems. Someone should either use asdf to choose a Julia version or they should use juliaup to choose a version and this makes it very likely that both tools will try to do something, causing a bad interaction.
