### ISSUE TITLE
Use launchd on Mac for background update task

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#215]
At the moment we use cron, but launchd seems better on Mac.

**Comment by staticfloat** [comment]
Agreed; I've done some launchd debugging myself recently, due to [using launchd to restart macos buildkite agents](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/main/macos-seatbelt/common.jl#L217-L281), and I found [LaunchControl](https://www.soma-zone.com/LaunchControl/) to be an indispensable resource for debugging why my scripts were failing.  If you run into troubles, I highly recommend downloading that app and addressing any of the lint failures it notes.

**Comment by fingolfin** [comment]
Just wondering, but: what about using `launchd` would be better than using `cron`? I mean, sure, `launchd` is the "mac-ish" solution. But surely there should be a strong argument, as doing this will increase the code complexity and add yet another code variant to test and debug.

So: What are relevant issues with `cron` on mac, resp. advantage of `launchd`?

**Comment by davidanthoff** [comment]
To be perfectly honest, I'm not even sure we should keep the cron thing around.. I think in practice the checks that happen when one launches `julialauncher` are probably good enough.

**Comment by fingolfin** [comment]
Agreed. But that seems like yet another reason to close this issue ;-)

**Comment by StefanKarpinski** [comment]
I think it would be fine to have instructions on how to setup a cron job, rather than trying to do it automatically.
