### ISSUE TITLE
Allow disable prompting or answer "yes" to all questions

### ISSUE THREAD

**Issue by jlapeyre** [JuliaLang/juliaup#253]
Doing non-interactive installation is sometimes needed for installing to containers and for test environments. Perhaps via environment variables. 

Hope this is not a dup. I looked for a while.

I am not sure when `with_prompt` is called. `juliaup` is already installed on my machine. When I try to add a new version with `juliaup add x.y.z` I get no prompting. But, at least the first time I installed julia, I was prompted.

**Comment by calebwin** [comment]
I desperately need this as well...

**Comment by davidanthoff** [comment]
I think the only case where we have interactivity at the moment is the initial install, if it is done via the shell script route. And agreed, we should add a quiet option there, plus also command line arguments to configure all the things that one can configure via prompts at the moment.

**Comment by jlapeyre** [comment]
Just a reminder. I am trying to install Julia via juliaup in a docker container. Unless someone has another idea, I think this is a blocker.

**Comment by DanteOz** [comment]
I would also be interested in this use case.

**Comment by willtebbutt** [comment]
I would also be very keen to make this use-case possible. At the minute, it's unclear to me how one should automatically install JuliaUp in a non-interactive manner, which is important to me for automating the set up of new machines

**Comment by blegat** [comment]
It's a bit confusing at the moment because in the install script at https://install.julialang.org, it says `Unable to run interactively. Run with -y to accept defaults, --help for additional options` but the line 95 is commented out:
```
            # "-y"|"--yes")       _y=yes; need_tty=no ;; # skip prompt; no need for /dev/tty
```
so passing `-y` doesn't actually work

**Comment by Roger-luo** [comment]
Same issue here, we are trying to build an AMI for EC2 instances and this seems to be a blocking issue.  I'm wondering what's the blocking item here that preventing this feature/bug being fixed?

**Comment by mgiugliano** [comment]
@blegat I encountered the same issue, while trying to install juliaup on Google Colab.

Uncommenting line 95, everything proceeds and the `juliaup` executable is downloaded and launched. But it too prompts the user and fails in my use case (i.e. within a cell of a jupyter notebook, invoking shell commands, user interaction is not allowed).

**Comment by Roger-luo** [comment]
I had a brief look into the code, it seems the prompt comes from the new self-update code in rust. I'm not sure how to change that, however.

**Comment by MilesCranmer** [comment]
Hey, just pinging this. This is really important to have. I'm building a docker container and I'm pretty much forced to use the base Julia image despite Julia being just one of several dependencies, since I literally can't use `juliaup` in a non-interactive way.

@davidanthoff why did you comment out the `-y` option in commit https://github.com/JuliaLang/juliaup/commit/4ed907bc8ca9835bb951ac0289a6436b59aa0196? Could this be reverted ASAP?

**Comment by MilesCranmer** [comment]
I really needed this so I came up with a workaround to get things working with the existing script, which I share below.

Surprisingly you can't just do `echo '\n' | juliaup.sh`. I think rustup (which juliaup based on) checks for interactivity in a non-standard way which makes this not work.

This workaround requires linux's [expect](https://linux.die.net/man/1/expect) tool. It also assumes that the user prompt ends with `Cancel installation`. If that changes, this will break.

Anyways, here's the non-interactive install script, given you've downloaded the existing shell script to `juliaup-init.sh`
```sh
#!/usr/bin/expect
spawn juliaup-init.sh
expect "Cancel installation"
send -- "\r"
expect eof
```
This will wait for "Cancel installation" to show up, and then send a carriage return back. That's all you need.

Here's my docker commands which let you use juliaup:

```dockerfile
RUN apt-get update && apt-get install -y expect && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install juliaup:
RUN curl -fsSL https://install.julialang.org -o /tmp/install-julia.sh && \
    echo '#!/usr/bin/expect\nspawn /tmp/install-julia.sh\nexpect "Cancel installation"\nsend -- "\\r"\nexpect eof' >> /tmp/install-julia.exp && \
    chmod +x /tmp/install-julia.sh && \
    chmod +x /tmp/install-julia.exp && \
    /tmp/install-julia.exp && \
    rm /tmp/install-julia.sh && \
    rm /tmp/install-julia.exp
```

This works, which lets you now use `juliaup` inside a dockerfile!

**Comment by davidanthoff** [comment]
Here is a rough roadmap to implement this feature. I won't get to it anytime soon, but maybe this helps someone else.

The first set of changes is in the shell script that bootstraps the actual binary `juliainstaller` onto a system:
1. Reenable https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/deploy/shellscript/juliaup-init.sh#L90 and https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/deploy/shellscript/juliaup-init.sh#L95.
2. Pass a flag to the `juliainstaller` binary (that is written in Rust) to do a quiet install in this line https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/deploy/shellscript/juliaup-init.sh#L136. Note that this flag does not yet exist in `juliainstaller`!

The second set of changes is that we need to add a quiet option to `juliainstaller`. Roughly that involves:
1. Adding some command line argument for a quiet mode at https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/src/bin/juliainstaller.rs#L93.
2. If that flag is set, skip all the interactive steps in `juliainstaller` (https://github.com/JuliaLang/juliaup/blob/main/src/bin/juliainstaller.rs) and use the defaults instead. I think that should be relatively simple, it essentially would just mean that in https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/src/bin/juliainstaller.rs#L237-L277 we would not show the prompt and be done.
3. In quiet mode disable https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/src/bin/juliainstaller.rs#L170.

A more comprehensive solution of course would add many more command line argument options so that one can specify values for all the choices that the interactive wizard offers at the moment, but I think that could presumably be a second step?

**Comment by MilesCranmer** [comment]
Here is a one-liner to use this:

```bash
expect -c 'spawn bash -c "curl -fsSL https://install.julialang.org | sh"; expect "Proceed"; send -- "\r"; expect eof'
```

**Comment by affans** [comment]
@MilesCranmer would it be possible for you to post a complete docker file? I am trying to run the command you gave, but hitting an error due to a slim base version. 
```
Step 5/9 : RUN expect -c 'spawn bash -c "curl -fsSL https://install.julialang.org | sh"; expect "Proceed"; send -- "\r"; expect eof'
 ---> Running in f42e76bca0a4
spawn bash -c curl -fsSL https://install.julialang.org | sh

bash: line 1: curl: command not found
``` 
where the Dockerfile is 
```
FROM debian:bullseye-slim

#RUN useradd --create-home juliauser
#USER juliauser # don't login as user since permission issues
#RUN chmod 700 install.jl

RUN apt-get -y update
RUN apt-get -y install git

RUN apt-get install -y expect && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN expect -c 'spawn bash -c "curl -fsSL https://install.julialang.org | sh"; expect "Proceed"; send -- "\r"; expect eof'
RUN juliaup add 1.8.0
```

**Comment by feefladder** [comment]
Another easier solution (I came here with a quick search)
```
curl -fsSL https://install.julialang.org | sh -s -- -y 
```
