### ISSUE TITLE
Take JULIA_DEPOT_PATH into account

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#26]
At the moment everything is hard coded to store Julia versions in `~/.julia/juliaup`. We should change that to check whether `JULIA_DEPOT_PATH` is configured and then use the value there if present.

**Comment by heetbeet** [comment]
I would really love this feature, I snooped around a bit and found the following two places where the `~/.julia/juliaup` path is assumed:
https://github.com/JuliaLang/juliaup/blob/0bfe67d43677f50d148bd97deb47551d511ea825/Juliaup/src/Juliaup.jl#L19
https://github.com/JuliaLang/juliaup/blob/0bfe67d43677f50d148bd97deb47551d511ea825/launcher/launcher.cpp#L310

What I wonder is 
- How do the different versions of Julia handle the environment variable?
- Will it require more work that just using `DEPOT_PATH[0]` in the julia code and something like `Is JULIA_DEPOT_PATH empty? Then return "~/.julia/juliaup" else return JULIA_DEPOT_PATH (split at ";")` in the C++ part?
- Does this issue break version-compatibility? https://github.com/JuliaLang/julia/issues/31002
- And if version compatibility is broken, does it matter? I.e. what do we want to do when an old version of Julia doesn't understand `JULIA_DEPOT_PATH` and uses `~/.julia` or something else, while juliahub wants to use `JULIA_DEPOT_PATH/juliahub`. My current thinking is that this might actually be preferred since then at least juliahub will always be consistent and located where never versions would have wanted to place it.

I have a hunch that if we use `DEPOT_PATH[0]` in julia and add a preference for the environment variable `JULIA_DEPOT_PATH ` (split at `;`) in C++, we will be A-okay.

**Comment by davidanthoff** [comment]
Yeah, I think that should pretty much be it. Couple of more specifics:
- We can't use `DEPOT_PATH` in the Julia code because it isn't populated when `juliaup` is compiled with PackageCompiler. So on the Julia side we'll also have to look for the env variable explicitly, parse it ourselves and extract the right values etc. Should not be hard at all, though.
- I think your logic for the C++ code is spot on (and the same would be used in the Julia code). Only "extra" thing I can think of is that on non Windows platforms `:` is also a valid splitter in `JULIA_DEPOT_PATH`, and we might just make it cross platform compatible from the beginning?
- I agree, I think we should just ignore the "old" interpretation of `JULIA_DEPOT_PATH` and go with the new one that was introduced in #31002. I think this is such a corner case, I just can't imagine that would be a problem.
