### ISSUE TITLE
Support older glibc versions (e.g. glibc 2.12)

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/juliaup#321]
Right now, it looks like the distributed `juliaup` binaries for Linux do not support glibc 2.12.

To reproduce, first, run the following command:

```
docker run --rm -it centos:6
```

Now, inside the Docker container, run the following commands:

```
/lib64/libc.so.6
curl -fsSL https://install.julialang.org | sh
```

Here is the output that I get:

```
info: downloading installer
Warning: Not enforcing strong cipher suites for TLS, this is potentially less secure
Warning: Not enforcing TLS v1.2, this is potentially less secure
/tmp/tmp.sFLAXI1M2z/juliainstaller: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /tmp/tmp.sFLAXI1M2z/juliainstaller)
/tmp/tmp.sFLAXI1M2z/juliainstaller: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/tmp.sFLAXI1M2z/juliainstaller)
/tmp/tmp.sFLAXI1M2z/juliainstaller: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/tmp.sFLAXI1M2z/juliainstaller)
```

**Comment by evetion** [comment]
Would be great to have this 👍🏻

**Comment by Wongboo** [comment]
Really a issue

**Comment by tpmerrifield** [comment]
Also ran into this on Red Hat Enterprise version 7.9, GLIBC_2.18 not found.

**Comment by DilumAluthge** [comment]
My understanding is that statically linking glibc is strongly discouraged.

Statically linking musl is an option. One challenge is the DNS resolver. For example, musl's DNS resolver does not support TCP, so if the result is too big to fit in a UDP packet, musl truncates it and returns only some of the results. I'm not sure if this would be a problem in practice, but it's at least a theoretical concern.

We already have the infrastructure in Buildkite for building Julia with support for old glibc. (The support varies based on architecture. For x86_64, we support glibc as old as 2.12.2.) So it's really just a matter of using our existing tooling to build the $ARCH-linux-gnu binaries for Juliaup.

**Comment by LilithHafner** [comment]
glibc is tier 1, so I think this blocks release and advertisement on the downloads page of juliaup as the official Julia version manager.

**Comment by StefanKarpinski** [comment]
@davidanthoff, is there anything anyone could do to help you out on this one? I seem to recall agreement that static linking musl would be an acceptable approach since we don't really care about `juliaup` using the system DNS resolver (it only looks up `julialang.org` which is not something that should be messed with). I also recall some issue that you had to work out about an upgrade path but I can't find that discussion now.

**Comment by davidanthoff** [comment]
The problem is that the self-update mechanism in Juliaup constructs the download URLs for its updates from the platform string of itself, so the glib version will always look for an update version that has `glib` not `musl` in the download URL. We essentially need to find some way to switch the folks on the glib version over to the musl version.

BUT, I think we could in the short term just compile both the glib and the musl version, publish both and then keep the glib folks on that version for now, and point new users to a musl version. That should all be relatively easy, it gives us some time to test a musl build, and then we can still think about a strategy to move folks over down the road.

**Comment by davidanthoff** [comment]
I'm building musl versions now as part of the normal release process. Things that still need to be done:
- [ ] Add musl versions to CI testing
- [ ] Update install shell script to return the musl builds on the platforms where we want that (I think all Linux distributions, right?)
- [ ] Generally test the musl build :)

I think we can actually skip the entire migration phase. The folks that have Juliaup already installed with the gnu libc can just stay on that version forever.

**Comment by davidanthoff** [comment]
Ok, seems all to work. There is still a problem with the testing, but I'll open a separate PR that tracks that.

**Comment by davidanthoff** [comment]
Try
```
curl -fsSL https://install.julialang.org/releasepreview | sh
```
The new build is not yet on the Juliaup release channel, only on the releasepreview, until we've tested it properly.
