### ISSUE TITLE
Explore linux

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/juliaup#38]
Maybe one could actually make something like `sudo apt install julia` install a packaged version of the launcher from this repo here and `juliaup`...

**Comment by heetbeet** [comment]
To port launcher.cpp might require maintaining a nix and a win version of some of the functions. Might be a good idea to split out the OS specific functionality in order to swop them out for each platform's compilation pipeline.

From a birds-eye view:
- The string `ConvertXxxToYyy` functions might not be necessary for nix
- The functions `GetLastErrorAsString`, `ArgvQuote`, `StartProcess`, `GetExecutablePath`, `GetHomedirPath` should be ported
 
Other things that might make the port easier:
- `GetUserProfileDirectoryA` might require a form of `std::getenv("PATH")`
- `ArgvQuote` will have to work a bit differently on nix since [Windows split args strangely](http://www.windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program)
- `SetConsoleTitle` might require playing around with [this](https://stackoverflow.com/a/49051066/1490584)
- `CreateProcessW` can be replaced with [fork+exec](https://gist.github.com/caiorss/133e91ba3732718cb228310173368674)

**Comment by davidanthoff** [comment]
I think that is all correct, but we might not even need to do anything: I'm in the middle of rewriting everything in Rust, including the launcher. If that plan works out as I hope it will, it will hopefully abstract all these platform specific things more or less away.

**Comment by davidanthoff** [comment]
I'm closing for now, because in principle `juliaup` and `julialauncher` work on Linux now, we can now open more targeted issues.
