### ISSUE TITLE
Print help on `julia update` in case of no update

### ISSUE THREAD

**Issue by hexaeder** [JuliaLang/juliaup#387]
First of all: thanks for building juliaup. Relinking `julia` command to different versions is so convenient! So much better than the system of symbolics links I was using before!

However I ran into kinda the same problem two times in a row which might have been prevented quite easily. I am on MacOS. As soon as i saw the`1.8-rc4` announcement on discourse I ran `juilaup update`, which immedeately returned without any output. I thought mit might take some time for the releases to be picked up so i tried the next day - didn't work. After looking through the readme I tried `juliaup self update`(didn't work) and ended up updating juliaup through brew. I could install the new version then. A week later, `1.8` was released and I went through nearly the same proceedure because I have the memory of a goldfish.

**What would have helped me:** add helpfull output to `juliaup update` like 
```
~> juliaup up
No new Julia versions found. Consider updating juliaup.
```
or better
```
~> juliaup up
No new Julia versions found. There is a new version of juliaup available, try this!
```
or even better
```
~> juliaup up
Found new julia version XXX on channel xxx, update juliaup to X.X.XX to install new julia version.
```

Sidequestion: Why is that even necessary? Will it allways be neccessary to update `juliaup` to fetch a new release? juliaup feels like some kind of package manager and I wouldn't expect to update the manager in order to update a package.

**Comment by shayandavoodii** [comment]
The funny thing now is that it's been almost four days since the first release of Julia `1.8.1`, and there has been no update on Juliaup till now.

**Comment by davidanthoff** [comment]
Julia 1.8.1 is not out yet, the trigger for me to release it is the discourse announcement. The existence of the tag in the Julia repo does _not_ mean that it is available, that only starts the release process.

Juliaup is self-updating, or it should be, so I don't really think we need additional messages. BUT, I am working on a solution so that Juliaup will know about new Julia versions without a new Juliaup shipping. I think once that is in place it should fully address your concern, right?
