### ISSUE TITLE
Don't crash on invalid shell startup files

### ISSUE THREAD

**Issue by FireSpike0** [JuliaLang/juliaup#433]
Hi everyone,

when trying to install Juliaup on my machine, the installer itself crashes immediately after downloading the Juliaup file. During the installation I just kept all settings on their defaults. To install Juliaup I used the recommended `curl` method described within the README file.

The generated crash report:
```
name = 'Juliainstaller'
operating_system = 'unix:Arch'
crate_version = '1.7.24'
explanation = '''
Panic occurred in file 'src/operations.rs' at line 675
'''
cause = 'called `Result::unwrap()` on an `Err` value: stream did not contain valid UTF-8'
method = 'Panic'
backtrace = '''

   0: 0x55c073266e04 - juliainstaller::main::h84fedc54940da11e
   1: 0x55c073251d23 - std::sys_common::backtrace::__rust_begin_short_backtrace::hed5660ccc12c4739
   2: 0x55c073251fd1 - std::rt::lang_start::{{closure}}::h2c3639270a40ed75
   3: 0x55c07326acf2 - main
   4: 0x7f41f3890290 - <unresolved>
   5: 0x7f41f389034a - __libc_start_main
   6: 0x55c073251539 - _start
   7:        0x0 - <unresolved>'''
```

**Comment by wolthom** [comment]
@FireSpike0 This is just a guess without digging too deep:
Do you have any non-UTF8 characters in your path or in your `.zshrc` / `.bashrc` / ...?

Narrowing this down further would probably require building a new `juliaup` version with additional context in the error message.

**Comment by StefanKarpinski** [comment]
That would be my guess as well. Unfortunately file systems basically all allow invalid Unicode (true on UNIX where it's invalid UTF-8 and true on Windows where it's potentially invalid UTF-16). For that reason paths in Rust use different types that permit invalid Unicode and you have to unwrap that get a string and that unwrapping operation can fail if the path contains invalid data. What's extra annoying about this is that string operations would work just fine if the language's string type weren't so pedantic about this (which is why Burnt Sushi made a [popular string library](https://blog.burntsushi.net/bstr/) that allows invalid data in strings; this is how Julia's built-in String type works). Anyway, the upshot is that you probably need to avoid converting to string here to be robust against invalid path names.

**Comment by davidanthoff** [comment]
My best guess is that this is crashing [here](https://github.com/JuliaLang/juliaup/blob/b13ebd7a764404442dea59e3861769f476c0a2a7/src/operations.rs#L596). We read the content of your startup shell scripts there, so if there is any non UTF-8 character in say your `.zshrc` file or something like that it will crash. We can't get around this by using specific path types, the code there is manipulating the content of these files to add the Juliaup folder to the `PATH`, so I guess what we really need to do is make that code work with non UTF-8 files, if it is actually legal on Unix to have shell scripts that contain non UTF-8 characters...

To get a better error message that would confirm my hypothesis, we would replace

```
file.read_to_string(&mut buffer)?;
```
with something like
```
file.read_to_string(&mut buffer)
    .with_context(|| "Failed to put file content into UTF-8 string type.")?;
```

**Comment by wolthom** [comment]
@davidanthoff As we briefly discussed, I would be interested in taking a shot at this.
If I had to take a guess, this could be related to environment variables / file system paths in the shell startup scripts. Since non-UTF-8 Paths are allowed, this is the most likely offender.

While googling around a little, there are a number of issues where other applications stumbled over similar problems (e.g. homebrew).

My suggested approach would be to move the file handling from the implicit UTF8-requirement to working with raw bytes.
We do not add non-ASCII characters to the shell startup script under any circumstances, right?
If so, the byte-approach should even be compatible with ASCII-only files.

Finally, regarding the implementation:
- Is the block managed by `juliaup` supposed to be replaced in its entirety when already present?
- When not present, it should just be appended to the end, right?
- Would you mind taking a dependency on `regex`? (That would probably be the easiest solution. Just use the `regex::bytes` functionality and match+replace the entire block.)

**Comment by davidanthoff** [comment]
> My suggested approach would be to move the file handling from the implicit UTF8-requirement to working with raw bytes.

Sounds right.

> We do not add non-ASCII characters to the shell startup script under any circumstances, right?

Not from our end. We might end up handling non-ASCII characters in a path, I guess, but if we just pass them through unmodified that should all work, right?

> If so, the byte-approach should even be compatible with ASCII-only files.

Yes, agreed.

> Is the block managed by `juliaup` supposed to be replaced in its entirety when already present?

Yes.

> When not present, it should just be appended to the end, right?

Yep.

> Would you mind taking a dependency on `regex`? (That would probably be the easiest solution. Just use the `regex::bytes` functionality and match+replace the entire block.) Edit: `bstr` should suffice and is probably much lighter than `regex`

I'm really only concerned about dependencies for `julialauncher`, I'm trying to keep that as small as possible in terms of binary size. But for `juliaup` and `julialauncher` I think it really doesn't matter much. I'm really not good with regex in general, so that was probably the primary reason I just went with an entirely hand rolled implementation ;)

I think essentially all the changes you would have to make are confined to https://github.com/JuliaLang/juliaup/blob/c50a4af79be93a51adb76027ea96c6403f8f0b29/src/operations.rs#L575-L685.
