### ISSUE TITLE
"Juliaup configuration is locked by another process, waiting for it to unlock."

### ISSUE THREAD

**Issue by roland-KA** [JuliaLang/juliaup#598]
I'm currently testing some command-line Julia scripts. After calling such a script for the first time like 

`julia --project=@. myscript.jl`

I often cannot run it again. Trying to run it a second time, I typically get the following error message:

"Juliaup configuration is locked by another process, waiting for it to unlock."

It works, if I'm waiting for some time between the calls. This is quite annoying. How and why does `juliaup` interfere with these calls?

I've installed Julia using `juliaup`.

Here is my versioninfo:
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 

```

**Comment by milankl** [comment]
Also just hit this. Through a slurm queue on a linux cluster, as well as in interactive sessions on the same node. I cannot even start the REPL by typing `julia`, without getting a similar error message to above. Also rfourquet's work-around hits a similar error. I can, however, launch julia by `.julia/juliaup/julia-1.8.5+0.x64.linux.gnu/bin/julia`

**Comment by davidanthoff** [comment]
Dup of https://github.com/JuliaLang/juliaup/issues/435.

**Comment by hraftery** [comment]
#435 seems related but not the core issue here. It relates to performing a lengthy operation and not being able to do anything else in the meantime. Here the issue is:

```
% julia myscript.jl # launches script, but also launches the self check in the background!
% julia myscript2.jl # fails because the self check reliably hangs
```

In that case the user is powerless because they didn't start the process. I had to resort to finding and killing the background process. The workaround [here](https://github.com/JuliaLang/juliaup/issues/598#issuecomment-1499023304) does seem to be the best option at the moment.

**Comment by davidanthoff** [comment]
This should be entirely fixed on main.
