### ISSUE TITLE
Don't crash when profile files are read-only

### ISSUE THREAD

**Issue by sunwenjin27** [JuliaLang/juliaup#624]
I cannot down load juliaup.
[report-fc39d574-69c6-4160-b41d-8c6f99a5dedd.toml.zip](https://github.com/JuliaLang/juliaup/files/11354227/report-fc39d574-69c6-4160-b41d-8c6f99a5dedd.toml.zip)

**Comment by davidanthoff** [comment]
Full error log from that file is
```
name = 'Juliainstaller'
operating_system = 'unix:OSX'
crate_version = '1.8.16'
explanation = '''
Panic occurred in file 'src/operations.rs' at line 749
'''
cause = '''
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/sunwenjin/.bash_profile.

Caused by:
    Permission denied (os error 13)'''
method = 'Panic'
backtrace = '''

   0: 0x104e50a88 - juliaup::command_config_modifypath::run_command_config_modifypath::h0f87529dd7cef58e
   1: 0x104d970a8 - juliainstaller::main::h6342f9beb07f076b
   2: 0x104d800d4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hda91fd22e5148544
   3: 0x104d9cb7c - _main'''

```

**Comment by uncomfyhalomacro** [comment]
This seems to be a user setup. The permission denied error means that the operation is not allowed without elevated privileges. :thinking:

**Comment by jjvliu** [comment]
I think I understand this issue. I encountered a slight variation of this (`.profile` instead of `.bash_profile`) after resolving #631 for myself. I can't speak for sunwenjin27 nor #630, but in my case the reason is clear: my sysadmin does not allow modification of `.profile` so the file is read-only. Instead I manage other dotfiles to be executed later. I was however temporarily able to give myself write permission on `.profile` which allowed me to complete the installation successfully.

I get this error even if I select "no" when asked "Do you want to add the Julia binaries to your PATH by manipulating various shell startup scripts? (y/n)". If this option is disabled, can we change the following?

1. Not open .profile, or open it in read-only mode.
2. Print some information about what the user should add to shell startup scripts.

It would also be good to have the installer suggest disabling the option if any shell startup script is read-only.

**Comment by jjvliu** [comment]
The solution above also probably resolves #565 and possibly #469.

**Comment by SaadiSave** [comment]
@jjvliu 

In the following code, shouldn't the match statement already prevent juliaup from opening the startup script at all when the user selects 'No':

https://github.com/JuliaLang/juliaup/blob/61c09c460ca3a150e542522be8b8b8a5041e718a/src/command_config_modifypath.rs#L13-L54

**Comment by uncomfyhalomacro** [comment]
> I think I understand this issue. I encountered a slight variation of this (`.profile` instead of `.bash_profile`) after resolving #631 for myself. I can't speak for sunwenjin27 nor #630, but in my case the reason is clear: my sysadmin does not allow modification of `.profile` so the file is read-only. Instead I manage other dotfiles to be executed later. I was however temporarily able to give myself write permission on `.profile` which allowed me to complete the installation successfully.
> 
> I get this error even if I select "no" when asked "Do you want to add the Julia binaries to your PATH by manipulating various shell startup scripts? (y/n)". If this option is disabled, can we change the following?
> 
>     1. Not open .profile, or open it in read-only mode.
> 
>     2. Print some information about what the user should add to shell startup scripts.
> 
> 
> It would also be good to have the installer suggest disabling the option if any shell startup script is read-only.

Not sure if I am correct here, wouldn't it be better to modify shellrc e.g. `.bashrc`, `.zshrc` rather than `.profile`? `.profile`, `.bash_profile`, `.zprofile` are for only read on login

**Comment by SaadiSave** [comment]
@uncomfyhalomacro

On my system, juliaup seems to modify both `.zshrc` and `.profile`
