### ISSUE TITLE
Can´t add channel using Mac M1

### ISSUE THREAD

**Issue by jplicona** [JuliaLang/juliaup#675]
I´m trying to install any channel in my Mac M1, but for some reason it is not working. I have been trying to fix this issue for several hours, try any possible combination and its not working. Do yoy guys if the server is down?

Thanks in advance

```
juliaup add release~x64
Error: Failed to update versions db.

Caused by:
    0: Failed to download current version db version.
    1: https://julialang-s3.julialang.org/juliaup/RELEASECHANNELDBVERSION: Network Error: timed out reading response
    2: timed out reading response
```

**Comment by davidanthoff** [comment]
Can you download `https://julialang-s3.julialang.org/juliaup/RELEASECHANNELDBVERSION` manually?

**Comment by jplicona** [comment]
yes, but i just get "1.0.24" inside the file. Is that okay? how and where do i need to paste this file? Thanks
<img width="681" alt="image" src="https://github.com/JuliaLang/juliaup/assets/113462297/bcd79c5e-1e26-49da-b515-7c23fbb6b23c">

**Comment by davidanthoff** [comment]
So my best guess is that the package we used in Juliaup to download stuff runs into some network problem and can't download that file... I have since switched over to a different package for downloading, and I just pushed out the latest version of Juliaup to everyone that uses this new download package.

BUT, you might not be able to use Juliaup itself to update to the latest version of Juliaup if my theory is correct. What I would recommend is that you uninstall with `juliaup self uninstall`, and then just install again with the curl command. That should give you the latest version of Juliaup with the new download code, and hopefully that will just resolve the problem.

**Comment by davidanthoff** [comment]
@jplicona is this resolved now with the latest version?

**Comment by ncihnegn** [comment]
On M1 it incorrectly install x64.
```
$ ~/.juliaup/bin/juliaup add lts                                            
Installing Julia 1.6.7+0.x64.apple.darwin14
```

**Comment by davidanthoff** [comment]
I believe we are falling back to x64 for Julia 1.6 because there are no aarch64 builds (or maybe they just aren't officially supported?). I would assume that for something like 1.9 you should get the correct aarch64 build, right?

But in any case, this seems an entirely unrelated issue from the original post?

**Comment by ncihnegn** [comment]
A message indicating fallback will be informative.

**Comment by fingolfin** [comment]
I think the original issue is resolved, though?

**Comment by davidanthoff** [comment]
Yes, lets close this and if the other issue still exists, please open a new issue!
