### ISSUE TITLE
Specifying flying toaster aliens as the release channel should throw

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/juliaup#714]
```
x@x top_secret % julia +1.0 -e 'println(VERSION)'                      
1.0.5
x@x top_secret % julia -e 'println(VERSION)' +1.0                      
1.9.2
x@x top_secret % julia -e +flying 'println(VERSION)' +toaster +aliens
1.9.2
```
Could be related to #713

**Comment by davidanthoff** [comment]
So, at the moment we _only_ allow the channel specifier in the first position. The reason is that I think we would have to mimic the entire command line parser in Julia itself to correctly figure out what is going on. And unfortunately I think one can't implement that without actually knowing the rules for specific flags...

Having said that, we probably have to replicate the original command line arg parser in any case at some point because it would be _very_ helpful if we would know whether Julia is going to run in an interactive mode, in which case we could show various interactive prompts.

**Comment by fingolfin** [comment]
But even if you parse the command line fully, is it really a good idea to allow `+CHANNEL` *anywhere*? What if I have a script that takes arguments which can start with `+`? Hell, I could even have a file starting with a `+`.

As long as we allow exactly one channel identifier at the start,  it's easy to deal with that. But if all arguments starting with `+` are potentially snatched away by `juliaup`, that could be problematic.

In the other direction, what would be a usecase that makes this useful to have in the first place?

**Comment by LilithHafner** [comment]
Agreed. exactly one specifier at the start would be good. Right now more arguments starting with a + are snatched away than should be.

```
x@fedora:~$ ~/.juliaup/bin/julia -e +error 'println("Hello")'
Hello
x@fedora:~$ ~/.local/bin/julia-1.11 -e +error 'println("Hello")'
ERROR: MethodError: no method matching +(::typeof(error))

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:595
  +(::BitMatrix, ::LinearAlgebra.UniformScaling)
   @ LinearAlgebra ~/.julia/juliaup/julia-fb8d7f1034/share/julia/stdlib/v1.11/LinearAlgebra/src/uniformscaling.jl:151
  +(::Bool, ::Complex{Bool})
   @ Base complex.jl:308
  ...

Stacktrace:
 [1] top-level scope
   @ none:1
x@fedora:~$ ~/.juliaup/bin/julia -e 'println(ARGS)' +arg
["+arg"]
x@fedora:~$ ~/.juliaup/bin/julia -e +arg 'println(ARGS)'
String[]
x@fedora:~$ ~/.juliaup/bin/julia +arg -e 'println(ARGS)'
ERROR: Invalid Juliaup channel `arg` at command line.
x@fedora:~$ ~/.juliaup/bin/julia -e arg 'println(ARGS)'
ERROR: UndefVarError: `arg` not defined
```
