### ISSUE TITLE
Symlink error when link/file exist

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/juliaup#773]
I already had the file `.juliaup/bin/julia` which resulted in the following error during installation:
```
Error: failed to create symlink `/Users/fredrik/.juliaup/bin/julia`.

Caused by:
    File exists (os error 17)
```

It seems like this case should be handled better. In my case the file that existed was already the correct symlink too.

**Comment by uncomfyhalomacro** [comment]
@fredrikekre can you please provide of this bug by exporting an env `RUST_BACKTRACE=full`? I will tackle this when I am free. This should be a fast fix I guess. Thanks!

**Comment by jlapeyre** [comment]
This happened to me as well. I had not used juliaup for a long time. `juliaup` is missing. But `~/bin/julialauncher` and configuration files and julia installations are present. I imagine this is not super uncommon. So `~/bin/julialauncher` exists and will start julia, but `juliaup` is not present.

The installation instructions say I should use curl to install the installer. I do this and the installer says it has found an existing configuration file. The only option it offers is to overwrite it. So I say "yes". It then ignores the existing julia installations and instead downloads and installs the latest stable version. It then fails to make the symlink to `~/.juliaup/julialauncher` because it is already there.  Because it fails, the next step, adding julialauncher to the path, does not happen. It turns out my installation is fine, other than this last fact. Because even thought it could not make the symlink, the symlink is already correct. I am not sure what modifications it planned to make to my path. So I give the curl command again. The installer is downloaded, and juliaup is downloaded again (even though it is already there). The latest configuration file is there, of course, but it is generated again. Then the installer downloads the latest stable version of julia and installs it over the existing installation that it made a few minutes earlier. I actually forgot to delete the symlink. So it fails again. I have to download the installer, juliaup, and the latest stable julia a third time. Now instructions for updating my `PATH` variable are printed. I have a working installation.

I think that the installer could do a better job of analyzing the existing juliaup installion. Both to be more informative to the user and to better recover from errors.

**Comment by mohamed-180** [comment]
Based on the discussion on [Julia discourse](https://discourse.julialang.org/t/installation-has-gotten-worse/118012/8) 

Would we add some guideline to remove previous julia installations completely before use juliaup installations and noted in installation page Or make it the in setup operations .
