### ISSUE TITLE
Microsoft store installation currently broken

### ISSUE THREAD

**Issue by heetbeet** [JuliaLang/juliaup#85]
When I installed Julia from the Microsoft store for the first time, I got the following `dll` linking error:
![image](https://user-images.githubusercontent.com/4103775/128259057-5cfb922a-1f46-4242-9820-9556822383b5.png)

Plus some of the dlls have strange filenames:
![image](https://user-images.githubusercontent.com/4103775/128259314-fd100504-2e04-4b5b-9626-1bcb8a55c884.png)

When I replaced the version with a working version from https://julialang-s3.julialang.org/bin/winnt/x64/1.6/julia-1.6.2-win64.zip, it worked again:
![image](https://user-images.githubusercontent.com/4103775/128259421-ad02d978-1664-44e8-a46b-c2ad52a41122.png)

**Comment by heetbeet** [comment]
Juliaup version 1.6.1 seems to be working fine with correctly named dlls:
![image](https://user-images.githubusercontent.com/4103775/128260070-9fceb9d7-0916-4c88-8d74-79677e0b1f8c.png)

**Comment by davidanthoff** [comment]
Hm, that is very strange, I just installed it fresh in a virtual machine and it all worked... The problem is definitely this mangled filenames, but why are you getting those and I'm not in my virtual machine?

Has anyone else seen this problem?

**Comment by davidanthoff** [comment]
Another diagnostic you would try: There are two "sources" where an installation can come from. The installer always bundles the latest version of Julia, and when you install it for the first time from the store, and `~/.julia/juliaup` doesn't exist, then it will copy the version of Julia that was inside the store distributed installer into the `juliaup` folder and mark that as the current version for the `release` channel. This is the _only_ time that this version out of the installer will be used. All other operations by `juliaup` download Julia from the web and use that version. So one thing that we should figure out first is whether this problem is present for both or only one source. I am assuming right now that this is a problem with the bundled version only.

You could test this by deleting the `release` channel with `juliaup rm release`, and then adding it again with `juliaup add release`. That should use the web-download version of Julia for the release channel, and we could see whether that also has the problem or not.

**Comment by heetbeet** [comment]
Sorry, my bad! I see I messed up while playing around with poking around the appx files. I tried to see how to extract the binaries from appx to see if my changes work, but it seems like it isn't a normal zip file that can be extracted, since it mangles the filenames:
![image](https://user-images.githubusercontent.com/4103775/128338092-4378c39b-914f-4e2b-83aa-1addbaa095b9.png)

So what probably happened was that I ran juliaup and then it copied that directory to `~/.julia/juliaup` and then when I installed the app from the MS store, it didn't see the need to overwrite the distro in `~/.julia/juliaup/julia-1.6.1+0~x64`.
