### ISSUE TITLE
Juliainstaller Crash Report

### ISSUE THREAD

**Issue by rcbarr1** [JuliaLang/juliaup#874]
Attempted to install Julia using "curl -fsSL https://install.julialang.org | sh" and got the following message:

"Well, this is embarrassing.

Juliainstaller had a problem and crashed. To help us diagnose the problem you can send us a crash report.

We have generated a report file at "/var/folders/hz/jsqbp65n72bgd53c3prn1q8h0000gp/T/report-10855ac7-c6a2-4623-bc1c-5cee2ba660a4.toml". Submit an issue or email with the subject of "Juliainstaller Crash Report" and include the report as an attachment.

- Homepage: https://github.com/JuliaLang/juliaup

We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.

Thank you kindly!"

The report file contains the following information:

"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.4.0 [64-bit]"
"crate_version" = "1.14.7"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/Reese/.zshrc.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x105923175 - core::result::unwrap_failed::h951d84d71b0bada2
   1: 0x105740aa2 - juliaup::command_config_modifypath::run_command_config_modifypath::h100e4c863f62efca
   2: 0x1055ef798 - juliainstaller::main::hb4c72525a8c2646f
   3: 0x1055d88a6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4c8c12f28586b664
   4: 0x1055f6843 - _main
   5: 0x7ff81a456366 - <unresolved>"""

I updated my Mac software from 14.1.1 to 14.4.0 and had the same issue both times.

**Comment by oneirica** [comment]
+1

"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.3.0 [64-bit]"
"crate_version" = "1.14.7"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/~/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"

**Comment by vyason** [comment]
+1

"name" = "Juliainstaller"
"operating_system" = "Mac OS 14.5.0 [64-bit]"
"crate_version" = "1.14.9"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1021
"""
"cause" = """
called `Result::unwrap()` on an `Err` value: Failed to open file /Users/vyas/.bash_profile.

Caused by:
    Permission denied (os error 13)"""
"method" = "Panic"
"backtrace" = """

   0: 0x1007dbd94 - core::result::unwrap_failed::h8e3b933261dd7fec
   1: 0x10069f990 - juliaup::command_config_modifypath::run_command_config_modifypath::hca63d35b576be3c9
   2: 0x1005af58c - juliainstaller::main::hb0bee2b2a4d9e158
   3: 0x10059b268 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2b1ac18042ef3658
   4: 0x1005b3c4c - _main"""
