### ISSUE TITLE
pre releases inflation

### ISSUE THREAD

**Issue by oheil** [JuliaLang/juliaup#989]
Those Releases tagged "pre release" flood my inbox. I am always hyped "great, a new release" and click, it's just a pre-release, meh.
Are these "Pre"-Releases really needed? If so, ok, than I will life with it. But if they don't have a purpose I would prefer not seeing them. What do other followers think?

**Comment by davidanthoff** [comment]
Unfortunately nothing we can do about this. I need to update the GitHub release workflow to use a new signing tool because our old certificate is going to expire in August, and there just is no other way to try out new code than to push and let it run for real. Hopefully I will  be done with this stuff soon, though.
